export const dashboard = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Steel Scale | Outreach desk</title><link rel="stylesheet" href="/console.css"></head><body>
<header><div><span class="brand">STEEL SCALE</span><h1>Outreach desk</h1><p>Relevant conversations. Clear next steps.</p></div><span class="badge">REVIEW MODE · NO AUTO SEND</span></header>
<main><section id="login"><h2>Open your workspace</h2><p>Your admin token stays in this tab's memory. Refreshing signs you out.</p><form id="login-form"><input id="token" type="password" autocomplete="off" placeholder="Admin token" required><button>Unlock</button></form></section>
<div id="workspace" hidden><div class="toolbar"><p id="setup"></p><button id="refresh">Refresh</button><button id="logout" class="secondary">Lock</button></div>
<div class="metrics"><div><strong id="total">0</strong><span>Prospects</span></div><div><strong id="due">0</strong><span>Follow-ups due</span></div><div><strong id="handoffs">0</strong><span>For Carson</span></div><div><strong>25</strong><span>Daily target · Mon–Sat</span></div></div>
<details><summary>Add researched prospects</summary><p>Paste a JSON array with name, company, linkedin_url, headline, signal, signal_url, signal_date (YYYY-MM-DD), qualification_evidence. Up to 50 rows. Check against your GHL baseline and prior batches before importing; this app only deduplicates LinkedIn profile identities.</p><textarea id="import" rows="6" placeholder='[{"name":"Example Owner","company":"Example Business","linkedin_url":"https://www.linkedin.com/in/example","signal":"Verified expansion announcement","signal_url":"https://example.com/news","signal_date":"2026-09-18","qualification_evidence":"Reviewed team and business size"}]'></textarea><button id="import-button">Import for review</button><pre id="import-result"></pre></details>
<div class="columns"><section><div class="toolbar"><h2>Prospects</h2><select id="filter"><option value="all">All</option><option value="due">Follow-up due</option><option value="handoff">For Carson</option><option value="active">Active</option></select></div><div id="list"></div></section>
<section id="detail"><h2>Choose a prospect</h2><p>Review the source, draft a message, then record the conversation here.</p></section></div></div><p id="notice" role="status"></p></main><script src="/console.js" defer></script></body></html>`;

export const css = `:root{color-scheme:dark;--bg:#111315;--panel:#1b1e22;--line:#353a40;--muted:#b0b6bc;--yellow:#ffd13b}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f4f4f2;font:15px/1.6 system-ui,sans-serif}header{padding:32px 5vw;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{color:var(--yellow);font-weight:900;letter-spacing:3px;font-size:12px}h1{font-size:36px;line-height:1.2;margin:10px 0}h2{font-size:21px;margin:0 0 14px}p{color:var(--muted)}header p{margin:0}.badge{border:1px solid var(--line);padding:7px 12px;border-radius:30px;font-size:11px;color:var(--yellow)}main{max-width:1500px;margin:auto;padding:28px 5vw}section,details{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:22px}button{background:var(--yellow);border:0;border-radius:7px;padding:11px 16px;font-weight:750;cursor:pointer;color:#141414}button:disabled{opacity:.5;cursor:wait}.secondary{background:#343940;color:white}input,textarea,select{font:inherit;background:#111315;color:white;border:1px solid #525a63;border-radius:6px;padding:10px;max-width:100%}textarea{width:100%;resize:vertical}input{width:100%}label{display:block;color:var(--muted);margin:12px 0 5px}.toolbar{display:flex;align-items:center;gap:12px;justify-content:space-between}.toolbar p{flex:1}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:20px 0}.metrics div{padding:18px;background:var(--panel);border:1px solid var(--line);border-radius:10px}.metrics strong{font-size:32px;display:block}.metrics span{color:var(--muted);font-size:12px}.columns{display:grid;grid-template-columns:340px minmax(0,1fr);gap:20px;margin-top:22px}.prospect{display:block;text-align:left;background:transparent;color:white;border:1px solid var(--line);width:100%;margin:8px 0;padding:12px}.prospect.selected{border-color:var(--yellow)}small{display:block;color:var(--muted)}a{color:var(--yellow)}.actions{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.turn{border-left:3px solid var(--line);padding:8px 14px;margin:12px 0;white-space:pre-wrap}.turn.inbound{border-color:var(--yellow)}.turn strong{font-size:11px;display:block;text-transform:uppercase}pre{white-space:pre-wrap;overflow-wrap:anywhere}#notice{position:sticky;bottom:10px;background:#24292f;border-radius:8px;padding:12px}#notice:empty{display:none}summary{cursor:pointer;font-weight:700}#login{max-width:550px;margin:25px auto}#login button{margin-top:14px}.warning{color:var(--yellow)}@media(max-width:850px){header{align-items:flex-start;flex-direction:column}.columns{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}`;

// All external text is rendered with textContent/value, never innerHTML.
export const script = `let token='',rows=[],selected=null,detail=null;
const $=id=>document.getElementById(id), el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e};
function notice(t){$('notice').textContent=t}
async function api(path,data){const r=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function run(fn){document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){notice(e.message)}finally{document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function refresh(){const setup=await api('/setup');$('setup').textContent='AI '+(setup.ai?'connected':'needs key')+' · GHL '+(setup.ghl?'configured':'needs webhook')+' · SMS not connected';rows=await api('/contacts');$('total').textContent=rows.length;$('due').textContent=rows.filter(r=>r.state==='active'&&r.next_follow_up&&r.next_follow_up<=Date.now()/1000).length;$('handoffs').textContent=rows.filter(r=>r.state==='handoff').length;renderList();if(selected)await open(selected)}
function renderList(){const list=$('list');list.replaceChildren();const filter=$('filter').value;for(const r of rows){if(filter==='due'&&!(r.state==='active'&&r.next_follow_up&&r.next_follow_up<=Date.now()/1000))continue;if(['active','handoff'].includes(filter)&&r.state!==filter)continue;const b=el('button');b.className='prospect'+(r.id===selected?' selected':'');b.append(el('strong',r.name||r.company||'Unnamed'),el('small',r.company||''),el('small',(r.suppressed?'DO NOT CONTACT':r.state||'Not enrolled')+' · '+r.icp_status));b.onclick=()=>run(()=>open(r.id));list.append(b)}if(!list.children.length)list.append(el('p','No prospects in this view.'))}
function field(root,label,value,lines){root.append(el('label',label));const e=el(lines?'textarea':'input');e.value=value||'';if(lines)e.rows=lines;root.append(e);return e}
function button(root,label,fn,secondary=false){const b=el('button',label);if(secondary)b.className='secondary';b.onclick=()=>run(fn);root.append(b);return b}
async function action(name,data={}){const result=await api('/contacts/'+selected+'/'+name,data);notice(result.status?'Handoff: '+result.status:'Saved.');await refresh();return result}
async function open(id){selected=id;detail=await api('/contacts/'+id);renderList();const c=detail.contact,s=detail.session,root=$('detail');root.replaceChildren(el('h2',c.name||'Prospect'),el('p',c.company||''));const link=el('a','Open personal LinkedIn profile');link.href=c.linkedin_url;link.target='_blank';link.rel='noopener noreferrer';root.append(link);
root.append(el('p','Fit: '+c.icp_status+' · State: '+(s?.state||'Not enrolled')+' · GHL: '+(detail.handoff?.status||'Not forwarded')));
if(c.suppressed){root.append(el('p','Permanently suppressed. No further outreach.'));return}
const source=field(root,'Verified business event',s?.signal,2),url=field(root,'Evidence URL',s?.signal_url),date=field(root,'Date checked',s?.signal_date||new Date().toISOString().slice(0,10)),qual=field(root,'Business fit and identity evidence',s?.qualification_evidence,2);const evidenceButtons=el('div');evidenceButtons.className='actions';root.append(evidenceButtons);button(evidenceButtons,'Save evidence',()=>action('evidence',{signal:source.value,signal_url:url.value,signal_date:date.value,qualification_evidence:qual.value}),true);button(evidenceButtons,'Confirm ICP fit',()=>action('qualify'),true);
const controls=el('div');controls.className='actions';root.append(controls);button(controls,'Pause',()=>action('state',{state:'paused'}),true);button(controls,'Resume',()=>action('state',{state:'active'}),true);button(controls,'Take over',()=>action('state',{state:'handoff'}));button(controls,'Do not contact',async()=>{if(confirm('Permanently suppress this profile?'))await action('suppress')},true);
root.append(el('h2','Conversation'));for(const t of detail.turns){const box=el('div');box.className='turn '+t.direction;box.append(el('strong',t.direction==='inbound'?'Prospect':'Recorded as sent'),el('span',t.body));root.append(box)}
const inbound=field(root,'Paste their reply',null,3);button(root,'Record reply',async()=>{if(!inbound.value.trim())throw new Error('Enter the reply first');await action('inbound',{event_id:crypto.randomUUID(),message:inbound.value})},true);
root.append(el('p',s?.next_follow_up?'Next follow-up: '+new Date(s.next_follow_up*1000).toLocaleString():'No follow-up scheduled.'));
if(s?.summary)root.append(el('p','For Carson: '+s.summary));
if(s?.state==='handoff'){button(root,'Forward handoff to GHL',()=>action('handoff'));root.append(el('p','This triggers your configured GHL workflow. A delivered webhook is not a booked meeting.'));return}
const draft=field(root,'Review and edit the suggested message',s?.draft_text,5);const drafts=el('div');drafts.className='actions';root.append(drafts);button(drafts,'Draft next message',()=>action('draft'));button(drafts,'Save edits',()=>action('edit',{message:draft.value,version:s?.version}),true);button(drafts,'Copy saved draft',async()=>{if(!s?.draft_text)throw new Error('Generate and save a draft first');await navigator.clipboard.writeText(s.draft_text);notice('Copied. Send manually on LinkedIn after reviewing.')},true);button(drafts,'I sent the saved draft',async()=>{if(confirm('Confirm you manually sent the saved message on LinkedIn?'))await action('sent',{version:s?.version})},true);root.append(el('p','Sending and connection acceptance are manual. Only record an actual sent message. Follow-up timing starts when you record it.'))}
$('login-form').onsubmit=e=>{e.preventDefault();token=$('token').value;run(async()=>{await refresh();$('token').value='';$('login').hidden=true;$('workspace').hidden=false;notice('Workspace unlocked.')})};$('logout').onclick=()=>location.reload();$('refresh').onclick=()=>run(refresh);$('filter').onchange=renderList;$('import-button').onclick=()=>run(async()=>{const result=await api('/import',{rows:JSON.parse($('import').value)});$('import-result').textContent=JSON.stringify(result,null,2);await refresh()});`;
